same_num_of_test
Dostoyewski/KTViz pull request #13
Opened 2021-08-09 13:18 UTC by Amgaran

change generator

2021-08-09 15:39 UTC, Dostoyewski requested changes, later dismissed
@Amgaran точно ли генератор покрывает тестами все пространство вокруг нашего судна?

2021-08-09 15:39 UTC, Dostoyewski commented on generator.py
> +        while len(danger_points) < self.n_tests:
Почему `while`? `for` работает на порядок быстрее.

2021-08-09 15:39 UTC, Dostoyewski commented on generator.py
> +            [is_dang, v0, vt, CPA, TCPA] = self.dangerous(dist, tar_c, t_c_diff)
Почему детерминированная генерация? Обеспечит ли переход к количеству тестов равномерное покрытие всего пространства вокруг нашего судна тестами?

2021-08-09 15:41 UTC, Dostoyewski commented
@mangoozt можешь тоже глянуть?

2021-08-10 08:56 UTC, Amgaran commented on generator.py
> +        while len(danger_points) < self.n_tests:
`while` потому что это гарантирует, что на каждом расстоянии будет наперед заданное число тестов, а не будет, как раньше, уменьшаться с увеличением расстояния.

2021-08-10 08:57 UTC, Amgaran commented on generator.py
> +            [is_dang, v0, vt, CPA, TCPA] = self.dangerous(dist, tar_c, t_c_diff)
В каком плане детерминированная?
Равномерность должна обеспечиваться тем, что распределение фон Мизеса с параметрами (0, 0) вырождается в равномерное на промежутке [0, 2 * \pi]. Использую именно его, чтобы, если потом потребуется, была возможность сгенерировать больше тестов в окрестности некоторого угла.

2021-08-10 09:00 UTC, Amgaran commented
> @Amgaran точно ли генератор покрывает тестами все пространство вокруг нашего судна?

Не все пространство, а только потенциально опасное. Например, не имеет смысла добавлять вариант с целью на расстоянии 10 миль, которая будет ровно слева от нашего судно и будет иметь противоположное направление, поскольку не является опасной.

2021-08-10 11:03 UTC, mangoozt requested changes
нужно сделать сохранение сразу в metainfo.csv без записи файлов в папки

2021-08-10 14:29 UTC, Dostoyewski commented
А как же возможность посмотреть результаты?

2021-08-10 14:31 UTC, Dostoyewski commented
@mangoozt @Amgaran предлагаю просто добавить флаг для сохранения папок, который в дефолте не выставлен.

2021-08-10 14:35 UTC, Dostoyewski commented on generator.py
> +            [is_dang, v0, vt, CPA, TCPA] = self.dangerous(dist, tar_c, t_c_diff)
Я предлагаю пеленг сделать детерминированным, а разницу курсов через фон Мизеса. Так мы точно покроем все пространство тестами.

2021-08-10 14:35 UTC, Dostoyewski commented on generator.py
> +            [is_dang, v0, vt, CPA, TCPA] = self.dangerous(dist, tar_c, t_c_diff)
Но это уже на твоё усмотрение.

2021-08-10 14:36 UTC, mangoozt commented
> А как же возможность посмотреть результаты? 

результаты чего?

2021-08-10 14:37 UTC, Dostoyewski commented on generator.py
> +        while len(danger_points) < self.n_tests:
При переходе к одному не СВ параметру можно будет оставить `for`. Но это опять же, на твоё усмотрение.

2021-08-10 14:37 UTC, mangoozt commented
результаты генерации можно увидеть в таблице. А результаты тестирования в таблице с результатами тестирования.
но флаг, конечно, нужен

2021-08-10 14:41 UTC, Dostoyewski commented
Я про маневр, который будет построен. Ну, чтобы можно было тараканов погонять.

2021-08-10 14:43 UTC, Dostoyewski commented
Хотя можно тупо `json` с маневром сохранять.

2021-08-10 18:26 UTC, mangoozt commented
можно отдельно генерировать папку с входными для интересующего теста

2021-08-12 11:53 UTC, mangoozt approved these changes

2021-08-12 11:53 UTC, merged